GET http://localhost:5000/products

###
GET http://localhost:5000/products/3

###
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 100
}

###
PATCH http://localhost:5000/products/4
Content-Type: application/json

{
    "name": "Product 3 update",
    "price": 240
}

###
DELETE http://localhost:5000/products/12